// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Utils from "./Utils.bs.mjs";
import * as React from "react";
import * as Qrcode from "qrcode";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  var canvasRef = React.useRef(null);
  var originContent = Utils.getURLContent(undefined);
  var match = React.useState(function () {
        return originContent;
      });
  var setContent = match[1];
  var content = match[0];
  var match$1 = React.useState(function () {
        return location.href;
      });
  var setUrl = match$1[1];
  var url = match$1[0];
  var match$2 = React.useState(function () {
        return "";
      });
  var setTip = match$2[1];
  var tip = match$2[0];
  var onInput = function ($$event) {
    var value = $$event.target.value;
    Curry._1(setContent, (function (param) {
            return value;
          }));
  };
  return JsxRuntime.jsxs("main", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Share Your Text Content",
                      className: "text-2xl font-bold mb-4 dark:text-white"
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx("textarea", {
                            className: "w-full max-w-lg p-2 rounded-md border border-gray-300 dark:border-gray-700 dark:bg-gray-800 dark:text-white resize-y",
                            id: "content",
                            placeholder: "Enter your text content here...",
                            value: content,
                            onInput: onInput
                          }),
                      className: "flex flex-col items-center justify-center space-y-4"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("button", {
                                      children: "Create URL",
                                      className: "w-1/2 max-w-lg dark:bg-blue text-white bg-black h-[36px] rounded",
                                      onClick: (function (param) {
                                          var url = Utils.updateURLContent(undefined, content);
                                          var el = canvasRef.current;
                                          if (!(el == null)) {
                                            Qrcode.toCanvas(el, url, (function (err) {
                                                    console.log(err);
                                                  }));
                                            return Curry._1(setUrl, (function (param) {
                                                          return url;
                                                        }));
                                          }
                                          
                                        })
                                    }),
                                JsxRuntime.jsx("div", {
                                      className: "w-[8px]"
                                    }),
                                JsxRuntime.jsx("button", {
                                      children: "Copy Content",
                                      className: "w-1/2 max-w-lg dark:bg-blue text-white bg-black h-[36px] rounded disabled:opacity-80 disabled:cursor-not-allowed",
                                      disabled: content === "",
                                      onClick: (function (param) {
                                          Utils.copyText(content);
                                          Curry._1(setTip, (function (param) {
                                                  return "Copied successfully";
                                                }));
                                          setTimeout((function (param) {
                                                  Curry._1(setTip, (function (param) {
                                                          return "";
                                                        }));
                                                }), 1000);
                                        })
                                    })
                              ],
                              className: "w-full flex"
                            }),
                        JsxRuntime.jsx("h2", {
                              children: "Your QR Code",
                              className: "text-xl font-bold dark:text-white"
                            }),
                        JsxRuntime.jsx("div", {
                              children: JsxRuntime.jsx("canvas", {
                                    ref: Caml_option.some(canvasRef),
                                    className: "w-full h-full"
                                  }),
                              className: "w-64 h-64 bg-gray-200 rounded-md flex items-center justify-center"
                            }),
                        JsxRuntime.jsx("button", {
                              children: "Copy Link",
                              className: "w-full flex justify-center items-center max-w-lg dark:bg-blue text-white bg-black h-[36px] rounded disabled:opacity-80 disabled:cursor-not-allowed",
                              disabled: content === "",
                              onClick: (function (param) {
                                  Utils.copyText(url);
                                  Curry._1(setTip, (function (param) {
                                          return "Copied successfully";
                                        }));
                                  setTimeout((function (param) {
                                          Curry._1(setTip, (function (param) {
                                                  return "";
                                                }));
                                        }), 1000);
                                })
                            }),
                        tip !== "" ? JsxRuntime.jsx("div", {
                                children: tip,
                                className: "text-green-500"
                              }) : ""
                      ],
                      className: "flex flex-col items-center justify-center space-y-4 mt-8"
                    })
              ],
              className: "flex flex-col items-center justify-center min-h-screen bg-gray-100 dark:bg-gray-900 p-4"
            });
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
